name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Read version and image name from file
        id: version
        run: |
          echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
          echo "IMAGE_NAME=$(cat IMAGE_NAME)" >> $GITHUB_ENV

      - name: Build and push latest Docker Image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:latest

      - name: Build and push by version
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:${{env.VERSION}}
